# SPDX-FileCopyrightText: 2025 SAP SE
#
# SPDX-License-Identifier: Apache-2.0

[default.extend-words]

[files]
extend-exclude = [
  "go.mod",
  "static/alpinejs@3.11.1.js",
  "static/purecss-responsive@3.0.0.css",
  "static/purecss@3.0.0.css",
]
