# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0
version = 1
SPDX-PackageName = "maintenance-controller"
SPDX-PackageDownloadLocation = "https://github.com/sapcc/maintenance-controller"

[[annotations]]
path = [
  ".github/CODEOWNERS",
  ".github/renovate.json",
  ".gitignore",
  ".license-scan-overrides.jsonl",
  ".license-scan-rules.json",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "go.mod",
  "go.sum",
  "Makefile.maker.yaml",
  "vendor/modules.txt",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "static/*",
  "PROJECT",
  ".github/.kubebuilder-version",
  "hack/boilerplate.go.txt",
  "e2e/cluster.json",
]
SPDX-FileCopyrightText = "2020 SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "static/alpinejs*",
]
SPDX-FileCopyrightText = "Copyright Â© 2019-2021 Caleb Porzio and contributors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "static/purecss*",
]
SPDX-FileCopyrightText = "Copyright 2013 Yahoo!"
SPDX-License-Identifier = "BSD-3-Clause"
